### ISSUE TITLE
Add ESD diodes

### ISSUE THREAD

**Issue by adamgreig** [cuspaceflight/OkGo#13]
Should protect all the connectors with ESD diodes, especially power, antennas and firing channels. I like Farnell 2368169.

**Comment by cillian64** [comment]
Similarly, remove the current pulldowns on the ignition outputs, they are entirely pointless.

**Comment by cillian64** [comment]
I've been sneezing a lot lately so I'll get the 0603, [2368174](http://onecall.farnell.com/bourns/cga0603mlc-24e/esd-suppressor-0603-24v-0-5pf/dp/2368174).
